services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT:-3000}:3000"
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_APP_URL=http://0.0.0.0:${APP_PORT:-3000}
    restart: unless-stopped
