/* ------------------------------------------------------------------ */
/*  Furniture catalog — pre-designed reusable decorative components    */
/* ------------------------------------------------------------------ */

import { FurnitureItem } from "./types";

/**
 * Each item has a `renderer` key that maps to a drawing function
 * in the renderer module. Coordinates are in a normalized unit square
 * (0,0) to (1,1) so the renderer can scale to any width/height.
 */
export const furnitureCatalog: FurnitureItem[] = [
  /* ======================== SEATING ======================== */
  {
    id: "sofa-3-seater",
    name: "3-Seater Sofa",
    category: "seating",
    width: 2.2,
    height: 0.9,
    suitableRooms: ["living room", "family room", "lounge", "media room"],
    renderer: "sofa-3",
    fill: "#8B7355",
    stroke: "#5C4A3A",
    rotatable: true,
    tags: ["sofa", "couch", "seating", "living"],
  },
  {
    id: "sofa-2-seater",
    name: "2-Seater Sofa",
    category: "seating",
    width: 1.6,
    height: 0.85,
    suitableRooms: ["living room", "family room", "lounge", "media room", "bedroom"],
    renderer: "sofa-2",
    fill: "#8B7355",
    stroke: "#5C4A3A",
    rotatable: true,
    tags: ["sofa", "couch", "seating", "loveseat"],
  },
  {
    id: "armchair",
    name: "Armchair",
    category: "seating",
    width: 0.8,
    height: 0.8,
    suitableRooms: ["living room", "family room", "lounge", "bedroom", "study"],
    renderer: "armchair",
    fill: "#9B8B75",
    stroke: "#6B5B4A",
    rotatable: true,
    tags: ["chair", "armchair", "seating"],
  },
  {
    id: "dining-chair",
    name: "Dining Chair",
    category: "seating",
    width: 0.45,
    height: 0.45,
    suitableRooms: ["dining", "kitchen", "dining room", "breakfast nook"],
    renderer: "dining-chair",
    fill: "#A0522D",
    stroke: "#6B3410",
    rotatable: false,
    tags: ["chair", "dining", "seating"],
  },
  {
    id: "office-chair",
    name: "Office Chair",
    category: "seating",
    width: 0.6,
    height: 0.6,
    suitableRooms: ["office", "study", "home office"],
    renderer: "office-chair",
    fill: "#444444",
    stroke: "#222222",
    rotatable: true,
    tags: ["chair", "office", "desk chair"],
  },

  /* ======================== TABLES ======================== */
  {
    id: "dining-table-6",
    name: "Dining Table (6-seat)",
    category: "table",
    width: 1.8,
    height: 1.0,
    suitableRooms: ["dining", "dining room", "kitchen"],
    renderer: "dining-table-rect",
    fill: "#DEB887",
    stroke: "#A0784A",
    rotatable: true,
    tags: ["table", "dining", "rectangular"],
  },
  {
    id: "dining-table-4",
    name: "Dining Table (4-seat)",
    category: "table",
    width: 1.2,
    height: 0.8,
    suitableRooms: ["dining", "dining room", "kitchen", "breakfast nook"],
    renderer: "dining-table-rect",
    fill: "#DEB887",
    stroke: "#A0784A",
    rotatable: true,
    tags: ["table", "dining", "small"],
  },
  {
    id: "coffee-table",
    name: "Coffee Table",
    category: "table",
    width: 1.1,
    height: 0.6,
    suitableRooms: ["living room", "family room", "lounge"],
    renderer: "coffee-table",
    fill: "#C4A882",
    stroke: "#8B7355",
    rotatable: true,
    tags: ["table", "coffee", "living"],
  },
  {
    id: "side-table",
    name: "Side Table",
    category: "table",
    width: 0.5,
    height: 0.5,
    suitableRooms: ["living room", "bedroom", "family room"],
    renderer: "side-table",
    fill: "#C4A882",
    stroke: "#8B7355",
    rotatable: false,
    tags: ["table", "side", "end table"],
  },
  {
    id: "desk",
    name: "Desk",
    category: "table",
    width: 1.4,
    height: 0.7,
    suitableRooms: ["office", "study", "home office", "bedroom"],
    renderer: "desk",
    fill: "#8B7355",
    stroke: "#5C4A3A",
    rotatable: true,
    tags: ["desk", "table", "office", "work"],
  },

  /* ======================== BEDS ======================== */
  {
    id: "bed-double",
    name: "Double Bed",
    category: "bed",
    width: 1.5,
    height: 2.0,
    suitableRooms: ["bedroom", "master bedroom", "guest room"],
    renderer: "bed",
    fill: "#E8E0D5",
    stroke: "#B8A99A",
    rotatable: true,
    tags: ["bed", "double", "sleeping"],
  },
  {
    id: "bed-queen",
    name: "Queen Bed",
    category: "bed",
    width: 1.6,
    height: 2.1,
    suitableRooms: ["bedroom", "master bedroom"],
    renderer: "bed",
    fill: "#E8E0D5",
    stroke: "#B8A99A",
    rotatable: true,
    tags: ["bed", "queen", "sleeping"],
  },
  {
    id: "bed-king",
    name: "King Bed",
    category: "bed",
    width: 1.9,
    height: 2.1,
    suitableRooms: ["master bedroom"],
    renderer: "bed",
    fill: "#F0E8DC",
    stroke: "#C4B5A5",
    rotatable: true,
    tags: ["bed", "king", "sleeping", "master"],
  },
  {
    id: "bed-single",
    name: "Single Bed",
    category: "bed",
    width: 1.0,
    height: 2.0,
    suitableRooms: ["bedroom", "guest room", "kids room"],
    renderer: "bed",
    fill: "#E8E0D5",
    stroke: "#B8A99A",
    rotatable: true,
    tags: ["bed", "single", "sleeping", "guest"],
  },

  /* ======================== BATHROOM ======================== */
  {
    id: "toilet",
    name: "Toilet",
    category: "bathroom",
    width: 0.45,
    height: 0.7,
    suitableRooms: ["bathroom", "ensuite", "powder room", "wc"],
    renderer: "toilet",
    fill: "#F5F5F5",
    stroke: "#CCCCCC",
    rotatable: true,
    tags: ["toilet", "bathroom", "wc"],
  },
  {
    id: "sink-bathroom",
    name: "Bathroom Sink",
    category: "bathroom",
    width: 0.6,
    height: 0.5,
    suitableRooms: ["bathroom", "ensuite", "powder room"],
    renderer: "sink-bathroom",
    fill: "#F5F5F5",
    stroke: "#CCCCCC",
    rotatable: true,
    tags: ["sink", "bathroom", "vanity"],
  },
  {
    id: "bathtub",
    name: "Bathtub",
    category: "bathroom",
    width: 0.75,
    height: 1.7,
    suitableRooms: ["bathroom", "ensuite"],
    renderer: "bathtub",
    fill: "#F5F5F5",
    stroke: "#D0D0D0",
    rotatable: true,
    tags: ["bath", "bathtub", "bathroom"],
  },
  {
    id: "shower",
    name: "Shower",
    category: "bathroom",
    width: 0.9,
    height: 0.9,
    suitableRooms: ["bathroom", "ensuite"],
    renderer: "shower",
    fill: "#E8F4FD",
    stroke: "#B0D0E8",
    rotatable: false,
    tags: ["shower", "bathroom"],
  },

  /* ======================== KITCHEN ======================== */
  {
    id: "kitchen-counter-straight",
    name: "Kitchen Counter",
    category: "kitchen",
    width: 2.4,
    height: 0.65,
    suitableRooms: ["kitchen", "kitchenette"],
    renderer: "kitchen-counter",
    fill: "#D4C5B2",
    stroke: "#A89880",
    rotatable: true,
    tags: ["counter", "kitchen", "worktop"],
  },
  {
    id: "kitchen-counter-small",
    name: "Small Counter",
    category: "kitchen",
    width: 1.2,
    height: 0.6,
    suitableRooms: ["kitchen", "kitchenette"],
    renderer: "kitchen-counter",
    fill: "#D4C5B2",
    stroke: "#A89880",
    rotatable: true,
    tags: ["counter", "kitchen", "small"],
  },
  {
    id: "kitchen-counter-corner",
    name: "L-Shaped Counter",
    category: "kitchen",
    width: 2.0,
    height: 2.0,
    suitableRooms: ["kitchen"],
    renderer: "kitchen-counter-l",
    fill: "#D4C5B2",
    stroke: "#A89880",
    rotatable: true,
    tags: ["counter", "kitchen", "corner", "l-shape"],
  },
  {
    id: "stove-4-burner",
    name: "Stove/Oven",
    category: "kitchen",
    width: 0.6,
    height: 0.6,
    suitableRooms: ["kitchen", "kitchenette"],
    renderer: "stove",
    fill: "#444444",
    stroke: "#222222",
    rotatable: true,
    tags: ["stove", "oven", "cooktop", "kitchen"],
  },
  {
    id: "refrigerator",
    name: "Refrigerator",
    category: "appliance",
    width: 0.8,
    height: 0.8,
    suitableRooms: ["kitchen", "kitchenette", "pantry"],
    renderer: "refrigerator",
    fill: "#E8E8E8",
    stroke: "#AAAAAA",
    rotatable: true,
    tags: ["fridge", "refrigerator", "kitchen", "appliance"],
  },
  {
    id: "kitchen-sink",
    name: "Kitchen Sink",
    category: "kitchen",
    width: 0.6,
    height: 0.5,
    suitableRooms: ["kitchen", "kitchenette", "laundry"],
    renderer: "kitchen-sink",
    fill: "#D0D0D0",
    stroke: "#999999",
    rotatable: true,
    tags: ["sink", "kitchen"],
  },
  {
    id: "kitchen-island",
    name: "Kitchen Island",
    category: "kitchen",
    width: 1.8,
    height: 0.9,
    suitableRooms: ["kitchen"],
    renderer: "kitchen-island",
    fill: "#D4C5B2",
    stroke: "#A89880",
    rotatable: true,
    tags: ["island", "kitchen", "counter"],
  },

  /* ======================== STORAGE ======================== */
  {
    id: "wardrobe",
    name: "Wardrobe",
    category: "storage",
    width: 1.2,
    height: 0.6,
    suitableRooms: ["bedroom", "master bedroom", "walk-in closet"],
    renderer: "wardrobe",
    fill: "#C4A882",
    stroke: "#8B7355",
    rotatable: true,
    tags: ["wardrobe", "closet", "storage", "bedroom"],
  },
  {
    id: "bookshelf",
    name: "Bookshelf",
    category: "storage",
    width: 0.8,
    height: 0.35,
    suitableRooms: ["living room", "office", "study", "bedroom"],
    renderer: "bookshelf",
    fill: "#A0784A",
    stroke: "#704020",
    rotatable: true,
    tags: ["bookshelf", "storage", "books"],
  },
  {
    id: "cabinet",
    name: "Storage Cabinet",
    category: "storage",
    width: 0.9,
    height: 0.45,
    suitableRooms: ["living room", "dining", "hallway", "laundry"],
    renderer: "cabinet",
    fill: "#C4A882",
    stroke: "#8B7355",
    rotatable: true,
    tags: ["cabinet", "storage"],
  },

  /* ======================== DECORATIVE ======================== */
  {
    id: "rug-large",
    name: "Large Rug",
    category: "decorative",
    width: 2.0,
    height: 1.4,
    suitableRooms: ["living room", "family room", "bedroom"],
    renderer: "rug",
    fill: "#D4A76A",
    stroke: "#B8955A",
    rotatable: true,
    tags: ["rug", "carpet", "decorative"],
  },
  {
    id: "plant-indoor",
    name: "Indoor Plant",
    category: "decorative",
    width: 0.4,
    height: 0.4,
    suitableRooms: ["living room", "hallway", "dining", "office", "bedroom"],
    renderer: "plant",
    fill: "#4CAF50",
    stroke: "#2E7D32",
    rotatable: false,
    tags: ["plant", "decorative", "green"],
  },
  {
    id: "tv-unit",
    name: "TV Unit",
    category: "decorative",
    width: 1.4,
    height: 0.4,
    suitableRooms: ["living room", "family room", "media room", "bedroom"],
    renderer: "tv-unit",
    fill: "#444444",
    stroke: "#222222",
    rotatable: true,
    tags: ["tv", "media", "entertainment"],
  },

  /* ======================== OUTDOOR ======================== */
  {
    id: "outdoor-table",
    name: "Outdoor Table",
    category: "outdoor",
    width: 1.4,
    height: 0.8,
    suitableRooms: ["porch", "veranda", "terrace", "balcony", "garden", "patio"],
    renderer: "dining-table-rect",
    fill: "#9E9E9E",
    stroke: "#757575",
    rotatable: true,
    tags: ["table", "outdoor", "patio"],
  },
  {
    id: "outdoor-chair",
    name: "Outdoor Chair",
    category: "outdoor",
    width: 0.5,
    height: 0.5,
    suitableRooms: ["porch", "veranda", "terrace", "balcony", "garden", "patio"],
    renderer: "armchair",
    fill: "#9E9E9E",
    stroke: "#757575",
    rotatable: true,
    tags: ["chair", "outdoor", "patio"],
  },
];

/**
 * Look up a furniture item by its catalog id.
 */
export function getFurnitureById(id: string): FurnitureItem | undefined {
  return furnitureCatalog.find((item) => item.id === id);
}

/**
 * Get all furniture suitable for a given room name.
 */
export function getFurnitureForRoom(roomName: string): FurnitureItem[] {
  const lower = roomName.toLowerCase();
  return furnitureCatalog.filter((item) =>
    item.suitableRooms.some((r) => lower.includes(r))
  );
}

/**
 * Get furniture by category.
 */
export function getFurnitureByCategory(category: string): FurnitureItem[] {
  return furnitureCatalog.filter((item) => item.category === category);
}
